In [4]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")
pd.options.display.max_rows = 155000
pd.options.display.max_columns = 500
pd.options.display.float_format = '{:20,.2f}'.format
seed = np.random.seed(66)

In [5]:
# !pip install openpyxl

In [28]:
data = pd.read_excel("C:\D Drive\Richa\S3\cloud\customer_data.xlsx")

In [29]:
data.columns.values

array(['Client_ID', 'Age_Category', 'State', 'Annual_Income',
       'Source_of_Income', 'Investment_Amount', 'Dependents',
       'Expected_ROI'], dtype=object)

In [30]:
print(data.dtypes)

Client_ID             int64
Age_Category         object
State                object
Annual_Income         int64
Source_of_Income     object
Investment_Amount     int64
Dependents            int64
Expected_ROI         object
dtype: object

In [31]:
data['Age_Category'] = data['Age_Category'].astype(str)

In [32]:
# data['AGE_BUCKET'] = pd.cut(data.Age_Category, [0,30,40,50,60,999] , labels = [1, 2, 3, 4, 5])
# Define a function to map Age_Category to numerical categories
def map_age_category(age_str):
    if age_str == '<30':
        return 1
    elif age_str == '30-40':
        return 2
    elif age_str == '40-50':
        return 3
    elif age_str == '50-60':
        return 4
    elif age_str == '>60':
        return 5
    else:
        return None  # Handle unexpected values

# Apply the mapping function to the Age_Category column
data['AGE_BUCKET'] = data['Age_Category'].apply(map_age_category)

In [33]:
list = []
for i in data['Expected_ROI']:
    if i == '<10%':
        list.append(4)
    elif i == '10-15%':
        list.append(3)  
    elif i == '15-25%':
        list.append(2)   
    else:
        list.append(1)    
          
data['TARGET_BUCKET'] = list

In [34]:
for i in data['AGE_BUCKET']:
    if i==1:
            data['Max_Investment'] = 0.6 * data['Annual_Income']
    elif i==2:
             data['Max_Investment'] = 0.5 * data['Annual_Income']
    elif i==3:
             data['Max_Investment'] = 0.3 * data['Annual_Income']
    elif i==4:
            data['Max_Investment'] = 0.2 * data['Annual_Income']
    else:
            data['Max_Investment'] = 0.1 * data['Annual_Income']

In [35]:
data.head()

,Client_ID,Age_Category,State,Annual_Income,Source_of_Income,Investment_Amount,Dependents,Expected_ROI,AGE_BUCKET,TARGET_BUCKET,Max_Investment
0,1,50-60,Karnataka,3085317,Corporate employee,625000,2,15-25%,4,2,"308,531.70"
1,2,>60,Haryana,3859127,self employed,2013889,2,>25%,5,1,"385,912.70"

In [36]:
data['Inv_Ratio'] = data['Max_Investment']/data['Investment_Amount']

In [37]:
data['Risk_Score_N'] = 1 - ((data['Dependents']*3 + data['Inv_Ratio']*4
                             + data['AGE_BUCKET']*3)*data['TARGET_BUCKET'])/100

In [38]:
print(data['Risk_Score_N'])

0                   0.60
1                   0.78
Name: Risk_Score_N, dtype: float64

In [39]:
list = []
for i in abs(data['Risk_Score_N']):
    if i <= 0.2:
        list.append('Conservative')
    elif i <= 0.4:
        list.append('Moderatively Conservative')  
    elif i <= 0.6:
        list.append('Moderatively Aggresive')    
    elif i <= 0.8:
        list.append('Aggresive')   
    else:
        list.append('Very Aggresive')    
          
data['Risk Profile'] = list

In [40]:
data['Risk Profile'].value_counts()

Risk Profile
Aggresive    2
Name: count, dtype: int64

In [41]:
data.head()

,Client_ID,Age_Category,State,Annual_Income,Source_of_Income,Investment_Amount,Dependents,Expected_ROI,AGE_BUCKET,TARGET_BUCKET,Max_Investment,Inv_Ratio,Risk_Score_N,Risk Profile
0,1,50-60,Karnataka,3085317,Corporate employee,625000,2,15-25%,4,2,"308,531.70",0.49,0.60,Aggresive
1,2,>60,Haryana,3859127,self employed,2013889,2,>25%,5,1,"385,912.70",0.19,0.78,Aggresive

In [42]:
# data[data['Risk Profile'] == 'Very Aggresive']

In [43]:
data['Amt_Investment'] = data[['Investment_Amount','Max_Investment']].min(axis=1)

In [44]:
data.shape

(2, 15)

In [45]:
# def get_company_list(dat1,dat2,col1,col2):
    
#     list = []
    
#     for i in dat1[col1]:
#         dat_1 = dat1[dat1[col1] == i]
#         for j in dat_1[col2]:
#             dat_2 = dat2[dat2[col2] == j][['Name', 'BSE Code', 'NSE Code', 'Industry', 'Current Price','Company_Rank']].sort_values("Company_Rank").head(10)
#             dat_2 = dat_2.sample(frac = 0.5)
#             dat_2['Client Id'] = dat_1['Client Id'] 
#             dat_2['Customer Name'] = dat_1['Name'] 
#             dat_2['Amt_Investment'] = dat_1['Amt_Investment'] 
#             dat_2 = dat_2[['Client Id','Customer Name','Amt_Investment','Name','BSE Code', 'NSE Code', 'Industry', 'Current Price']]
#             return dat_2 
# # pd.concat(dat1[['Client Id','Name','Amt_Investment']],dat_2)

In [75]:
def get_company_list(dat1,dat2,col1,col2):
    
    list = []
    
    for i in dat1[col1]:
        print(i)
        dat_1 = dat1[dat1[col1] == i]
        print(dat_1['Client_ID'])
        for j in dat_1[col2]:
#             print(j)
            dat_2 = dat2[dat2[col2] == j][[ 'Name','BSE Code', 'NSE Code', 'Industry', 'Current Price','Risk Profile','Company_Rank']].sort_values("Company_Rank").head(10)
            dat_2 = dat_2.sample(frac = 0.5).reset_index(drop = True)
#             dat_2['Client Id'] = dat_1['Client Id'] 
#             dat_2['Customer Name'] = dat_1['Name'] 
#             dat_2['Amt_Investment'] = dat_1['Amt_Investment'] 
#             dat_2 = dat_2[['Client Id','Customer Name','Amt_Investment','Name','BSE Code', 'NSE Code', 'Industry', 'Current Price']]
#         dat_2['Client Id'] = dat_1['Client Id'] 
#         dat_2['Customer Name'] = dat_1['Name'] 
#         dat_2['Amt_Investment'] = dat_1['Amt_Investment'] 
#         dat_2 = dat_2[['Client Id','Customer Name','Amt_Investment','Name','BSE Code', 'NSE Code', 'Industry', 'Current Price']]
            
        return dat_2

In [76]:
data_comp = pd.read_csv('C:\D Drive\Richa\S3\cloud\Data_Companies.csv')

In [83]:
results = get_company_list(data,data_comp,'Client_ID','Risk Profile').sort_values("Company_Rank").head(10)

1
0    1
Name: Client_ID, dtype: int64

In [84]:
results

,Name,BSE Code,NSE Code,Industry,Current Price,Risk Profile,Company_Rank
2,ITC,500875,ITC,Cigarettes,341.05,Aggresive,1.00
4,Life Insurance,543526,LICI,Finance & Investments,638.80,Aggresive,3.00
3,Bajaj Holdings,500490,BAJAJHLDNG,Finance & Investments,"6,578.65",Aggresive,4.00
1,Bank of India,532149,BANKINDIA,Banks - Public Sector,75.10,Aggresive,5.00
0,M & M,500520,M&M,Automobiles - Passenger Cars,"1,227.15",Aggresive,10.00